### PR TITLE
Mark the shared->sync conversion as unsafe

### PR DESCRIPTION
**Pull request by dwijnand**
I wondered if there was a way to model away from the hidden panic.

This is just an idea - does using 'unsafe' make sense in this scenario?  Interested in your thoughts.

### CODE REVIEW

**Comment by dwijnand** [comment]
Alternatives I thought of:
* using `TryFrom`, but that's nightly only
* just dropping the conversion entirely... 😄

**Comment by withoutboats** [comment]
It does not make sense to mark this function unsafe. There is no way to use this function incorrectly to violate a memory invariant - the caller does not need to prove the correctness of anything. Panicking is not unsafe.

What would be an unsafe function would be one in which the sync bit was *not* checked, and it was just unsafely upgraded to a SyncPointer. The cases in which such a function could be called safely are few and far between though: you have to somehow know from the source code that your SharedPointer is not an Rc. The whole point of this library is to erase that type information, so its fairly unlikely you can correctly uphold that invariant.

A third alternative would be to use `TryFrom`, so that users could handle the error rather than panicking. However, it seems unlikely for users to be able to handle that error properly: either they'd have to be able to fall back to a single threaded algorithm when the type wasn't threadsafe, or they'd have to be able and willing to do a deep clone of the wrapped type to construct their own SyncPointer.

A complete API would probably provide all three conversions. My personal preference would be:

* `SyncPointer: From<SharedPointer>`, which panics
* `SyncPointer: TryFrom<SharedPointer>`, which can return an error
* An additional unsafe conversion method or pointer which doesn't check the sync bool

I think that we can't have that API exactly because of a conflict with the blanket impls of `TryFrom` for types that implement `From`, but something along those lines.

I also want to follow the precedent in the standard library (e.g. bounds checking), in which the panicking API is the most ergomic API (in that case indexing), the fallible API is the next most ergonomic, and the unsafe API is the least ergonomic.

**Comment by dwijnand** [comment]
I see!  I understand now better how "unsafe" is defined in Rust.  Thank you.

But isn't panicking in a trait impl a bit too indirect?  When you index you make a conscious decision, but when you call `.into()` is it expected to maybe panic?

**Comment by withoutboats** [comment]
@dwijnand I think its fine for Into to panic (indexing is also controlled by a trait after all). I'm sure other people disagree, but I think the rule of thumb is this: can the user probably do something other than `unwrap` here? I think in many cases the answer is no: you've written some code that needs to send a shared pointer across threads, and if you can't do that your program crashes.

The exemplar use case here (which this library is kind of a stab in the dark at handling more elegantly) is some of the futures API's Waker stuff. Some people would like to implement single-threaded executors which don't use atomics, on the assumption you'll never try to wake them from another thread. Because they're designed for use cases that will be single threaded, panicking if you try to send the waker across to another thread is the correct decision: you've combined that executor with some library it is explicitly not designed to handle. We can't enforce this at compile time because the Waker API is designed to erase the type of the executor used to run the future (for a lot of really good reasons), and so the next best thing is panicking as early as possible.

There are other use cases where you maybe want to opportunistically introduce some parallelism *only if you can*, and that's where an API that returns an Option or a Result would be appropriate. That's why I think providing both would be a good idea.

**Comment by withoutboats** [comment]
But since `From` and `TryFrom` are incompatible, I see two options:

1. `From` impl + `try_into` and `try_from` inherent methods
2. `TryFrom` impl + `into` and `from` inherent methods.

I think the reason to prefer 1 is that I'm more likely to write a function which is parametric over `T: Into<SyncPointer>` than `T: TryInto<SyncPointer>`, because probably if I'm writing a function that needs a syncpointer, I can't handle the conversion error. Instead, callers who have a sharedpointer and want to call me, but also don't want to panick, should handle the error themselves.

What do you think?

**Comment by dwijnand** [comment]
Do you think the blanket `TryFrom<U> for T where T: From<U>` impl is wrong?

I'm happy with 1 - your reasoning sounds reasonable, and it has the side-benefit that it keeps the crate compilable in stable (so far).

**Pull request closed without merging**
