### PR TITLE
Make use of nightly's rc_into_raw_non_null

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by withoutboats** [comment]
Thanks for upstreaming this function into std (especially since it was quite a PITA with different iterations)!

I'd merge this right away except that this crate currently compiles on stable. Instead, I'd prefer to have a `nightly` cargo feature that turns on the use of the std path, until the std API is stabilized.

**Comment by dwijnand** [comment]
Sounds like a great idea.  Will do.

**Comment by dwijnand** [comment]
WDYT?  I think it looks verbose, but I don't know how to make it any terser.  Suggestions welcome.

**Comment by withoutboats** [comment]
One way I believe you could have made it less verbose is to use a macro instead of a function, so you dont have to duplicate it for rc and arc:

```rust
#[cfg(feature = "nightly")]
macro_rules! into_raw_non_null {
    ($var:ident : $t:ident) => { $t::into_raw_non_null($var) }
}

#[cfg(not(feature = "nightly"))]
macro_rules! into_raw_non_null {
    ($var:ident : $t:ident) => { unsafe { NonNull::new_unchecked($t::into_raw($var) as *mut _) } }
}

into_raw_non_null!(rc: Rc)
into_raw_non_null!(arc: Arc)
```

But I don't think the difference is significant, so I'm merging this PR. Thanks! :)

EDIT: Actually this wouldn't be much better because you'd need to make a function anyway for the function pointer..

I'm going to make another PR of my own to close #2 and then I'll publish a release.

**Pull request merged**
